Update latest dependencies, closes #1
Fallen-Breath/conditional-mixin pull request #10
Opened 2024-07-03 03:53 UTC by SteveKunG

This is hopefully fixes compiling issue with Forge/NeoForge 1.20.6+.
Note: I haven't tested in production yet.

2024-07-03 06:34 UTC, Fallen-Breath requested changes
Your changes breaks the compatibility for non java 21 runtime

2024-07-03 07:03 UTC, SteveKunG commented
Done! Is there anything else?

2024-07-03 07:16 UTC, Fallen-Breath commented
Please test your builds in production, espeically in older non-java-21 versions (e.g. mc 1.16, 1.18, 1.19)

2024-08-14 14:53 UTC, SteveKunG commented
Tested all version work fine.
Fabric/Forge 1.16.5, 1.18.2, 1.19.2, 1.20.1, 1.20.6, 1.21.1
NeoForge 1.20.6 and 1.21.1

Note: Forge below 1.20.1 when viewing conditional mixin in the mod menu will crash the game due to 
`java.lang.IllegalArgumentException: Root resources can only be filenames, not paths (no / allowed!)`
https://github.com/Fallen-Breath/conditional-mixin/blob/master/forge/src/main/resources/META-INF/mods.toml#L11

2024-08-14 15:17 UTC, Fallen-Breath commented on forge/build.gradle
> +configurations.configureEach {
what is this change for?

2024-08-14 15:20 UTC, SteveKunG commented on forge/build.gradle
> +configurations.configureEach {
A requirement for Forge version 50+ to able run on dev. (Still I can't get it to run on my machine)

I took from Architectury discord.
https://discord.com/channels/792699517631594506/792701725106634783/1272848116864909314

2024-08-17 19:42 UTC, merged